### ISSUE TITLE
Documentation editing pass

### ISSUE THREAD

**Issue by kspeakman** [fable-elmish/fable-elmish.github.io#43]
Does anyone mind if I do an editor's pass on the documentation? The purpose is to fix grammar, spelling, etc. Not to make substantive changes.

I'd also like to thank whoever submitted the documentation and apologize for English following the big ball of mud (non-)design pattern.

**Comment by MangelMaxime** [comment]
No problem with doing a pass on the documentation.

Grammar and spelling definitely need fixing :)
