### ISSUE TITLE
v4 subscription docs

### ISSUE THREAD

**Issue by kspeakman** [fable-elmish/fable-elmish.github.io#44]
Is it okay if I wrote some docs for subscriptions? Two I can think of: Migrating from v3 to v4. Creation and usage guidance. There should probably be a general v3 to v4 migration guide (separate issue). The other topic I can think of for the migration guide is termination.

**Comment by et1975** [comment]
Yes please!

**Comment by kspeakman** [comment]
Moved to elmish/elmish#259.
